FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install

RUN bun run generate:db
RUN cd apps/web && bun run build

EXPOSE 3000

# Start the frontend application
CMD ["bun", "start:frontend"]