## Build the docker image
## Push the docker image to docker hub
## SSH into our VM and start the new image

name: Deploy the frontend
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: . 
        file: ./docker/Dockerfile.frontend
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app-frontend:latest

    ## Step 3: SSH into the VM and restart the frontend container
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/todo-app
          docker compose pull frontend
          docker compose up -d frontend